// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoyjReGCe0Wpyt1mGq1juaul5mmXtK5QM',
    appId: '1:60102118980:web:b5f66e452ae82514bfb611',
    messagingSenderId: '60102118980',
    projectId: 'flutter-application-2-25cbb',
    authDomain: 'flutter-application-2-25cbb.firebaseapp.com',
    storageBucket: 'flutter-application-2-25cbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNk9d_VzyqH_EWtNwLbdpyAw-CubCkQTI',
    appId: '1:60102118980:android:1aa006b2bf37f6a7bfb611',
    messagingSenderId: '60102118980',
    projectId: 'flutter-application-2-25cbb',
    storageBucket: 'flutter-application-2-25cbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjU5YzIX3xx2BmvPKaK3QG1gp1hdSr40',
    appId: '1:60102118980:ios:46b62bd3d45c89e0bfb611',
    messagingSenderId: '60102118980',
    projectId: 'flutter-application-2-25cbb',
    storageBucket: 'flutter-application-2-25cbb.appspot.com',
    iosClientId: '60102118980-hdfv5gah6m5f3eb6mh47nidvnnlsvlkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgjU5YzIX3xx2BmvPKaK3QG1gp1hdSr40',
    appId: '1:60102118980:ios:46b62bd3d45c89e0bfb611',
    messagingSenderId: '60102118980',
    projectId: 'flutter-application-2-25cbb',
    storageBucket: 'flutter-application-2-25cbb.appspot.com',
    iosClientId: '60102118980-hdfv5gah6m5f3eb6mh47nidvnnlsvlkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
